### ISSUE TITLE
document kafka-jaas.conf requirement

### ISSUE THREAD

**Issue by chrylis** [thmshmm/confluent-systemd#2]
The scripts include a property telling Kafka to look at `/etc/kafka/kafka-jaas.conf`, but this file isn't present by default. I'm not sure whether it's more suitable to recommend that the user remove the line or add the file, but this step should be in the README.

**Comment by thmshmm** [comment]
Thanks @chrylis, I've removed the line and added some comments to the documentation as you proposed.
